version: '3'

services:
  webapplication1:
    image: webapplication1
    ports:
      - "59252:80"
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    links:
      - db
    depends_on:
       - "db"
    networks:
      - mynetwork
    deploy:
      replicas: 2

  db:
    image: postgres
    restart: always
    ports:
       - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
       - mynetwork

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynetwork

volumes:
  pgdata:
  minio1-data:

networks:
  mynetwork:
    driver: overlay