version: '3'

services:
 minio1:
  image: minio/minio
  volumes:
   - minidata1:/export
  ports:
   - "9001:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: W9J5XIE4M3T0YVSR52V7
   MINIO_SECRET_KEY: xmrPyNhU2VolKQTrxYAKk+te4peBJZzSW1M7WxjU
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio2:
  image: minio/minio
  volumes:
   - minidata2:/export
  ports:
   - "9002:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: W9J5XIE4M3T0YVSR52V7
   MINIO_SECRET_KEY: xmrPyNhU2VolKQTrxYAKk+te4peBJZzSW1M7WxjU
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio3:
  image: minio/minio
  volumes:
   - minidata3:/export
  ports:
   - "9003:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: W9J5XIE4M3T0YVSR52V7
   MINIO_SECRET_KEY: xmrPyNhU2VolKQTrxYAKk+te4peBJZzSW1M7WxjU
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio4:
  image: minio/minio
  volumes:
   - minidata4:/export
  ports:
   - "9004:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: W9J5XIE4M3T0YVSR52V7
   MINIO_SECRET_KEY: xmrPyNhU2VolKQTrxYAKk+te4peBJZzSW1M7WxjU
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

volumes:
  minidata1:
  minidata2:
  minidata3:
  minidata4:

networks:
 minio_distributed:
  driver: overlay