version: '3'

services:
  webapplication1:
    image: webapplication1
    expose:
      - "80"
    ports:
      - "59252:80"
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    links:
      - db
    depends_on:
       - "db"
    networks:
      - mynetwork

  db:
    image: postgres
    restart: always
    ports:
       - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
       - mynetwork

  minio1:
    image: minio/minio
    volumes:
      - minio1-data:/data
    ports:
      - "9001:9000"
    networks:
      - mynetwork
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLEZZ
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/data

volumes:
  pgdata:
  minio1-data:

networks:
  mynetwork:
    driver: bridge